# Generated by Django 6.0.4 on 2026-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Dishi Poa', max_length=100)),
                ('tagline', models.CharField(default='Fresh, Hot, On Time.', max_length=200)),
                ('phone', models.CharField(default='+254 700 000 000', max_length=20)),
                ('email', models.EmailField(default='hello@dishipoa.co.ke', max_length=254)),
                ('address', models.TextField(default='Nairobi, Kenya')),
                ('mpesa_till', models.CharField(blank=True, max_length=20)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=20)),
                ('mpesa_account', models.CharField(blank=True, default='DISHIPOA', max_length=50)),
                ('ordering_open_message', models.CharField(default='Order before cutoff time!', max_length=200)),
                ('ordering_closed_message', models.CharField(default='Ordering is closed for today. Check back tomorrow!', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_text', models.TextField(blank=True)),
                ('chef_name', models.CharField(blank=True, max_length=100)),
                ('chef_photo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
