# Generated by Django 6.0.4 on 2026-04-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('day_name', models.CharField(max_length=20)),
                ('main_item', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cutoff_time', models.TimeField(help_text='Orders close at this time e.g. 11:00')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MenuCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_quantity', models.PositiveIntegerField(default=50)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('order_position', models.PositiveIntegerField(default=0)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='menu.dailymenu')),
            ],
            options={
                'ordering': ['order_position', 'name'],
            },
        ),
    ]
